[package]
name = "poisson"
version = "0.1.0"
edition = "2024"

[dependencies]
contracts = "0.6.6"
ndarray = { version = "0.16.1", features = ["rayon"] }
ndarray-npy = "0.9.1"
npyz = "0.8.4"
num-traits = "0.2.19"
rayon = "1.11.0"
